export const adminConstants = {
  // Admin JWT key
  ADMIN_TOKEN: 'ADMIN_TOKEN',

  // Admin authentication actions
  LOGIN_REQUEST: 'ADMIN_LOGIN_REQUEST',
  LOGOUT: 'ADMIN_LOGOUT',

  // ClusterInfo actions
  GET_CLUSTER_INFO_REQUEST: 'GET_CLUSTER_INFO_REQUEST',

  // User setting actions
  GET_USER_SETTINGS_REQUEST: 'GET_USER_SETTINGS_REQUEST',
  ADD_USER_SETTING_REQUEST: 'ADD_USER_SETTING_REQUEST',
  UPDATE_USER_SETTING_REQUEST: 'UPDATE_USER_SETTING_REQUEST',
  DELETE_USER_SETTING_REQUEST: 'DELETE_USER_SETTING_REQUEST',
  
  // Group setting actions
  GET_GROUP_SETTINGS_REQUEST: 'GET_GROUP_SETTINGS_REQUEST',
  ADD_GROUP_SETTING_REQUEST: 'ADD_GROUP_SETTING_REQUEST',
  UPDATE_GROUP_SETTING_REQUEST: 'UPDATE_GROUP_SETTING_REQUEST',
  DELETE_GROUP_SETTING_REQUEST: 'DELETE_GROUP_SETTING_REQUEST',

  // Function setting actions
  GET_FUNCTION_SETTINGS_REQUEST: 'GET_FUNCTION_SETTINGS_REQUEST',
  ADD_FUNCTION_SETTING_REQUEST: 'ADD_FUNCTION_SETTING_REQUEST',
  UPDATE_FUNCTION_SETTING_REQUEST: 'UPDATE_FUNCTION_SETTING_REQUEST',
  DELETE_FUNCTION_SETTING_REQUEST: 'DELETE_FUNCTION_SETTING_REQUEST',

  // DataLab setting actions
  GET_DATALAB_SETTINGS_REQUEST: 'GET_DATALAB_SETTINGS_REQUEST',
  ADD_DATALAB_SETTING_REQUEST: 'ADD_DATALAB_SETTING_REQUEST',
  UPDATE_DATALAB_SETTING_REQUEST: 'UPDATE_DATALAB_SETTING_REQUEST',
  DELETE_DATALAB_SETTING_REQUEST: 'DELETE_DATALAB_SETTING_REQUEST',

  // DataLabGroup setting actions
  GET_DATALAB_GROUP_SETTINGS_REQUEST: 'GET_DATALAB_GROUP_SETTINGS_REQUEST',
  ADD_DATALAB_GROUP_SETTING_REQUEST: 'ADD_DATALAB_GROUP_SETTING_REQUEST',
  UPDATE_DATALAB_GROUP_SETTING_REQUEST: 'UPDATE_DATALAB_GROUP_SETTING_REQUEST',
  DELETE_DATALAB_GROUP_SETTING_REQUEST: 'DELETE_DATALAB_GROUP_SETTING_REQUEST',

  // InstanceType setting actions
  GET_INSTANCE_TYPE_SETTINGS_REQUEST: 'GET_INSTANCE_TYPE_SETTINGS_REQUEST',
  ADD_INSTANCE_TYPE_SETTING_REQUEST: 'ADD_INSTANCE_TYPE_SETTING_REQUEST',
  UPDATE_INSTANCE_TYPE_SETTING_REQUEST: 'UPDATE_INSTANCE_TYPE_SETTING_REQUEST',
  DELETE_INSTANCE_TYPE_SETTING_REQUEST: 'DELETE_INSTANCE_TYPE_SETTING_REQUEST',

  // InstanceTypeGroup setting actions
  GET_INSTANCE_TYPE_GROUP_SETTINGS_REQUEST: 'GET_INSTANCE_TYPE_GROUP_SETTINGS_REQUEST',
  ADD_INSTANCE_TYPE_GROUP_SETTING_REQUEST: 'ADD_INSTANCE_TYPE_GROUP_SETTING_REQUEST',
  UPDATE_INSTANCE_TYPE_GROUP_SETTING_REQUEST: 'UPDATE_INSTANCE_TYPE_GROUP_SETTING_REQUEST',
  DELETE_INSTANCE_TYPE_GROUP_SETTING_REQUEST: 'DELETE_INSTANCE_TYPE_GROUP_SETTING_REQUEST',

  // Storage setting actions
  GET_STORAGE_SETTINGS_REQUEST: 'GET_STORAGE_SETTINGS_REQUEST',
  ADD_STORAGE_SETTING_REQUEST: 'ADD_STORAGE_SETTING_REQUEST',
  UPDATE_STORAGE_SETTING_REQUEST: 'UPDATE_STORAGE_SETTING_REQUEST',
  DELETE_STORAGE_SETTING_REQUEST: 'DELETE_STORAGE_SETTING_REQUEST',

  // Clear post/put/delete action request
  CLEAR_ADMIN_REQUEST: 'CLEAR_ADMIN_REQUEST',
};