export const userConstants = {
  LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
  LOGOUT: 'USER_LOGOUT',

  USER_TOKEN: 'USER_TOKEN',
  APP_USER: 'APP_USER',

  // Get environment  
  GET_APP_RROFILE_REQUEST: 'GET_APP_RROFILE_REQUEST',
  GET_APP_RESOURCE_QUOTA_REQUEST: 'GET_APP_RESOURCE_QUOTA_REQUEST',
  GET_APP_DATALAB_SETTINGS_REQUEST: 'GET_APP_DATALAB_SETTINGS_REQUEST',
  GET_APP_INSTANCE_TYPE_SETTINGS_REQUEST: 'GET_APP_INSTANCE_TYPE_SETTINGS_REQUEST',
  GET_APP_STORAGE_SETTINGS_REQUEST: 'GET_APP_STORAGE_SETTINGS_REQUEST',
  GET_APP_FUNCTION_SETTINGS_REQUEST: 'GET_APP_FUNCTION_SETTINGS_REQUEST',
  

  // Datalab instance actions
  GET_DATALAB_INSTANCES_REQUEST: 'GET_DATALAB_INSTANCES_REQUEST',
  GET_DATALAB_INSTANCE_REQUEST: 'GET_DATALAB_INSTANCE_REQUEST',
  GET_DATALAB_INSTANCE_LOG_REQUEST: 'GET_DATALAB_LOG_REQUEST',
  ADD_DATALAB_INSTANCE_REQUEST: 'ADD_DATALAB_INSTANCE_REQUEST',
  UPDATE_DATALAB_INSTANCE_REQUEST: 'UPDATE_DATALAB_INSTANCE_REQUEST',
  DELETE_DATALAB_INSTANCE_REQUEST: 'DELETE_DATALAB_INSTANCE_REQUEST',

  // Function instance actions
  GET_FUNCTION_INSTANCES_REQUEST: 'GET_FUNCTION_INSTANCES_REQUEST',
  GET_FUNCTION_INSTANCE_REQUEST: 'GET_FUNCTION_INSTANCE_REQUEST',
  GET_FUNCTION_INSTANCE_LOG_REQUEST: 'GET_FUNCTION_INSTANCE_LOG_REQUEST',
  ADD_FUNCTION_INSTANCE_REQUEST: 'ADD_FUNCTION_INSTANCE_REQUEST',
  UPDATE_FUNCTION_INSTANCE_REQUEST: 'UPDATE_FUNCTION_INSTANCE_REQUEST',
  DELETE_FUNCTION_INSTANCE_REQUEST: 'DELETE_FUNCTION_INSTANCE_REQUEST',
  RESTART_FUNCTION_INSTANCE_REQUEST: 'RESTART_FUNCTION_INSTANCE_REQUEST',

  // Job instance actions
  GET_JOB_INSTANCES_REQUEST: 'GET_JOB_INSTANCES_REQUEST',
  GET_JOB_INSTANCE_REQUEST: 'GET_JOB_INSTANCE_REQUEST',
  GET_JOB_INSTANCE_LOG_REQUEST: 'GET_JOB_INSTANCE_LOG_REQUEST',
  KILL_JOB_INSTANCE_REQUEST: 'KILL_JOB_INSTANCE_REQUEST',

  // Clear post/put/delete action request
  CLEAR_APP_REQUEST: 'CLEAR_APP_REQUEST',
};

export const jobConstants = {
  JOB_SUCCESS: 'Success',
  JOB_RUNNING: 'Running',
  JOB_FAILURE: 'Failed',
  JOB_PENDING: 'Pending',
  JOB_KILLED: 'Killed',
  JOB_UNKONWN: 'Unknown',
}