export const userConstants = {
  LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
  LOGOUT: 'USER_LOGOUT',

  USER_TOKEN: '',
  APP_USER: 'APP_USER',
};

export const dashboardConstant = {
  GET_MODEL_NUMBER: 'GET_MODEL_NUMBER',
  GET_API_NUMBER: 'GET_ACTIVE_API_NUMBER',
  GET_MODEL_DASHBOARD_LIST: 'GET_MODEL_DASHBOARD_LIST',
  GET_API_DASHBOARD_LIST: 'GET_API_DASHBOARD_LIST',
};

export const modelConstant = {
  GET_MODEL_LIST: 'GET_MODEL_LIST',
  GET_MODEL_INFO: 'GET_MODEL_INFO',
  DELETE_MODEL_INFO: 'DELETE_MODEL_INFO',
  GET_MODEL_VERSION_LIST: 'GET_MODEL_VERSION_LIST',
  GET_MODEL_DETAIL: 'GET_MODEL_DETAIL',
  GET_MODEL_PATH: 'GET_MODEL_PATH',
};

export const apiConstant = {
  GET_API_LIST: 'GET_API_LIST',
  GET_API_DETAIL: 'GET_API_DETAIL',
  GET_MODEL_AND_VERSION: 'GET_MODEL_AND_VERSION',
  ADD_API: 'ADD_API',
  EDIT_API: 'EDIT_API',
  DELETE_API: 'DELETE_API',
};
